### ISSUE TITLE
History scrolls to the top after viewing a card's description

### ISSUE THREAD

**Issue by byarmis** [itsalaidbacklife/cuttle-front-vue#101]
Steps to reproduce:

1. Click on a card
2. View what it does
3. History's now at the top and you have to scroll back down to the bottom to see what's up

**Comment by itsalaidbacklife** [comment]
This will be resolved in the move-choice rework. The history will remain constantly present and instead, seeing what a card does will be managed with the move-choice overlay

![image](https://user-images.githubusercontent.com/6520704/146032018-ad87d1e5-a9fe-4a8c-8c27-7fd672f42001.png)

A side effect of this is that the history will always be up to date/at the bottom
