### ISSUE TITLE
Add link to Discord server

### ISSUE THREAD

**Issue by byarmis** [itsalaidbacklife/cuttle-front-vue#104]
I imagine right now there's a lot of overlap between users of Cuttle and members of the Discord server, but for those that aren't in both, adding an invite link might be nice.

If you want to keep the server more locked down or whatever, feel free to close this!

**Comment by itsalaidbacklife** [comment]
This is a good idea and something I've been hoping to get around to. Longer range, we should have a whole landing page and generally unauthenticated experience which could include social media links and explanation of the game
