### ISSUE TITLE
Resolving cards sometimes doesn't clear 9 limitation

### ISSUE THREAD

**Issue by byarmis** [itsalaidbacklife/cuttle-front-vue#115]
Not sure the exact steps to reproduce, but they were something along the lines of:

- Player A plays a 9, targeting an in-play Queen
- Player B plays a 6's one-off, removing some cards
- Player A plays a Jack, targeting an in-play 10
- Player B cannot replay their bounced Queen

**Comment by itsalaidbacklife** [comment]
Confirmed; those are the correct steps to reproduce
